apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer1-deployment
  namespace: kafka
  labels:
    app: producer1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer1
  template:
    metadata:
      labels:
        app: producer1
    spec:
      containers:
      - name: producer1-jvm
        image: docker.io/quarkus/producer1-jvm:latest
        imagePullPolicy: Never  # since the image is already loaded to cluster (https://iximiuz.com/en/posts/kubernetes-kind-load-docker-image/)
        ports:
        - containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  name: producer1-service
  namespace: kafka
spec:
  ports:
  - name: api
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: producer1
  type: ClusterIP