apiVersion: v1
kind: Service
metadata:
  name: redpanda-external-static
  namespace: kafka
spec:
  ports:
  - name: kafka-default
    nodePort: 30950 # this is set static in the kind config
    port: 9094
    protocol: TCP
    targetPort: 9094
  selector:
    app.kubernetes.io/component: redpanda-statefulset
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/name: redpanda
  type: NodePort