apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
  namespace: kafka
spec:
  chartRef:
    chartVersion: 5.9.15
  clusterSpec:
    statefulset:
      # -- Number of Redpanda brokers (Redpanda Data recommends setting this to the number of worker nodes in the cluster)
      replicas: 1
    external:
      enabled: true
      # domain: localhost
      type: NodePort
      addresses:
      - localhost
    listeners:
      kafka:
        external:
          default:
            enabled: true
            port: 9094
            # -- If undefined, `listeners.kafka.external.default.port` is used.
            advertisedPorts:
            - 31092 # this corresponds to the exposed nodeport
            tls:
              enabled: false
    tls:
      enabled: false
      certs:
        default:
          caEnabled: true